apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-service
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axion-ingestion-service
  template:
    metadata:
      labels:
        app: axion-ingestion-service
    spec:
      containers:
        - name: ingestion-service
          image: ghcr.io/iamminakshi/axion-ingestion-service-v2:633b5c8
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:Postgres%4012345@postgres-service:5432/axiondb"

