apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-service
  namespace: axion-app
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axion-ingestion-service
  template:
    metadata:
      labels:
        app: axion-ingestion-service
    spec:
      containers:
        - name: ingestion-service
          image: ghcr.io/contactanamika55/axion-ingestion-service:d931142
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          env:
            - name: DATABASE_URL
              value: "postgresql://admin:admin%40123@postgres-service:5432/mydb123"