name: Build & Push Container Image to GHCR

on:
push:
branches:
- main
workflow_dispatch:

env:
REGISTRY: ghcr.io
IMAGE_NAME: ${{ github.repository }}

# Required permission to push image to GHCR

permissions:
contents: read
packages: write

jobs:
build-and-push:
name: Build and Push Docker Image
runs-on: ubuntu-latest
steps:

  # Checkout repository
  - name: Checkout Code
    uses: actions/checkout@v4

  # Setup Docker Buildx
  - name: Setup Docker Buildx
    uses: docker/setup-buildx-action@v3

  # Login to GitHub Container Registry
  - name: Login to GHCR
    uses: docker/login-action@v3
    with:
      registry: ${{ env.REGISTRY }}
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}

  # Generate Docker image metadata
  - name: Docker Metadata
    id: meta
    uses: docker/metadata-action@v5
    with:
      images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      tags: |
        type=sha
        type=raw,value=latest,enable={{is_default_branch}}

  # Build and Push Docker Image
  - name: Build and Push
    uses: docker/build-push-action@v6
    with:
      context: .
      push: true
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      cache-from: type=gha
      cache-to: type=gha,mode=max
      
